### ISSUE TITLE
Seamless and remove the_content

### ISSUE THREAD

**Issue by jurdekker** [StoutLogic/acf-builder#80]
How can i make the Flexible Content seamless?
How can i remove the default the_content?

**Comment by stevep** [comment]
You can set the attributes on the group itself. 
See: https://github.com/StoutLogic/acf-builder/wiki/field-groups#overwriting-default-values

So for example:

```php
$builder = new StoutLogic\AcfBuilder\FieldsBuilder('my_field_group', [
    'hide_on_screen' => ['the_content'], 
    'style' => 'seamless'
]);
```

There is also a shorthand:

```php
$builder = new StoutLogic\AcfBuilder\FieldsBuilder('my_field_group');
$builder
    ->hideContentEditor()
    ->setGroupConfig('style', 'seamless');

```

**Comment by jurdekker** [comment]
I got a error `No such function: hideContentEditor`

```
<?php

namespace App;

use StoutLogic\AcfBuilder\FieldsBuilder;

$domain = new FieldsBuilder('domain');

$domain
    ->setLocation('post_type', '==', 'domain')
    ->hideContentEditor()
    ->setGroupConfig('style', 'seamless');

$domain
    ->addTrueFalse('alias', ['label' => 'Alias', 'ui' => 1])
        ->setInstructions('Een extra domeinnaam, ofwel een alias, is een aanvullende domeinnaam die dezelfde website toont als je hoofddomein.');

return $domain;
```

Full error:
```

Fatal error: Uncaught Error: Class 'App\StoutLogic\AcfBuilder\FieldsBuilder' not found in /Users/jurdekker/Desktop/JurDekker/support/web/app/themes/support/app/fields/domain.php:18 Stack trace: #0 /Users/jurdekker/Desktop/JurDekker/support/web/app/themes/support/app/setup.php(159): require_once() #1 [internal function]: App\{closure}('/Users/jurdekke...', 0) #2 /Users/jurdekker/Desktop/JurDekker/support/web/app/themes/support/vendor/illuminate/support/Collection.php(932): array_map(Object(Closure), Array, Array) #3 /Users/jurdekker/Desktop/JurDekker/support/web/app/themes/support/app/setup.php(160): Illuminate\Support\Collection->map(Object(Closure)) #4 /Users/jurdekker/Desktop/JurDekker/support/web/wp/wp-includes/class-wp-hook.php(286): App\{closure}('') #5 /Users/jurdekker/Desktop/JurDekker/support/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /Users/jurdekker/Desktop/JurDekker/support/web/wp/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #7 /Users/jurdekker/Desktop/JurDekker/ in /Users/jurdekker/Desktop/JurDekker/support/web/app/themes/support/app/fields/domain.php on line 18
```

**Comment by stevep** [comment]
@jurdekker I apologize, it turns out that `hideContentEditor` function is defined in another project of mine, that extends FieldsBuilder and not ACF Builder directly. 

You can achieve the same functionality by changing your code to:

```php
$domain
    ->setLocation('post_type', '==', 'domain')
    ->setGroupConfig('hide_on_screen', ['the_content'])
    ->setGroupConfig('style', 'seamless');
```

Again sorry for the confusion, I'll edit my response above too.
